AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  nodejs-sam-bootstrap
  SAM Template for nodejs-sam-bootstrap

Resources:
  SampleBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: "sample-bucket"