AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  nodejs-sam-bootstrap
  SAM Template for nodejs-sam-bootstrap
#####  Globals for Lambda functions #####
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        Region: "eu-west-1"

#####  Input Parameters #####
Parameters:
  Stage:
    Type: String
    Description: Parameter for getting the deployment stage
    Default: default

#####  Environment Variables #####
Mappings:
  StagesMap:
    sandbox:
      VariableName: Value
    staging:
      VariableName: Value
    production:
      VariableName: Value

#####  Template Conditions #####
Conditions:
  CreateSandboxResources: !Equals [!Ref Stage, sandbox]

Resources:
  ##### Applications #####
  SampleApplicationA:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./appA/template.yaml
      Parameters:
        Stage: !Ref Stage
        Username: !Ref Username
  
  SampleApplicationB:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./appB/template.yaml
      Parameters:
        Stage: !Ref Stage
        Username: !Ref Username
  
  SampleApplicationC:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./appC/template.yaml
      Parameters:
        Stage: !Ref Stage
        Username: !Ref Username

Outputs:
  Sample1Api:
    Description: "API Gateway endpoint URL to print Hello, World!"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sample1/"
  Sample2Api:
    Description: "API Gateway endpoint URL to print Hello, World!"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sample2/"